-- Your SQL goes here
CREATE TABLE sessions (
	id UUID PRIMARY KEY,
	sub UUID NOT NULL,
	public_key BYTEA NOT NULL,
	private_key BYTEA NOT NULL,
	started TIMESTAMPTZ NOT NULL,
	exp TIMESTAMPTZ NOT NULL,
	FOREIGN KEY (sub) REFERENCES users(id) ON DELETE CASCADE
);
