[package]
name = "auth1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebkey = { version = "0.3.2", features = ["jwt-convert"] }
jsonwebtoken = "7.2.0"
openssl = "0.10.35"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8.2", features = ["v4"] }
