[package]
name = "auth1"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
argon2 = "0.4.1"
axum = { version = "0.5.15", features = ["headers"] }
base64 = "0.13.0"
clap = { version = "3.2.17", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = "0.3.23"
indoc = "1.0.7"
jsonwebtoken = "8.1.1"
lettre = { version = "0.10.1", default-features = false, features = [
  "builder",
  "tokio1-rustls-tls",
  "tracing",
  "serde",
  "smtp-transport",
  "pool",
] }
openssl = "0.10.41"
rand = "0.8.5"
serde = { version = "1.0.144", features = ["derive"] }
serde_with = { version = "2.0.0", features = ["base64"] }
sqlx = { version = "0.6.1", features = [
  "runtime-tokio-rustls",
  "offline",
  "postgres",
  "time",
  "uuid",
] }
strfmt = "0.2.2"
thiserror = "1.0.32"
time = "0.3.14"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[features]
