[package]
name = "auth1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-web-httpauth = "0.5.1"
aes-gcm = "0.9.3"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.7", features = ["postgres", "r2d2", "chrono", "uuidv07"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures-util = "0.3.16"
jsonwebtoken = "7.2.0"
lettre = "0.9.6"
lettre_email = "0.9.4"
once_cell = "1.8.0"
openssl = "0.10.35"
pbkdf2 = "0.8.0"
r2d2 = "0.8.9"
r2d2_redis = "0.14.0"
rand_core = { version = "0.6.3", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.26"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[dev-dependencies]
actix-rt = "2.2.0"
regex = "1.5.4"
serde_json = "1.0.66"
