[package]
name = "auth1"
version = "0.1.9"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.4"
actix-web = "3.3.2"
actix-web-httpauth = "0.5.1"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.7", features = ["postgres", "r2d2", "chrono", "uuidv07"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
fast_chemail = "0.9.6"
futures-util = "0.3.16"
jsonwebkey = "0.3.4"
jsonwebtoken = "7.2.0"
lettre = { version = "0.10.0-beta.4", features = ["builder", "file-transport", "tracing"] }
once_cell = "1.8.0"
openssl = "0.10.36"
p256 = "0.9.0"
pbkdf2 = "0.8.0"
r2d2 = "0.8.9"
r2d2_redis = "0.14.0"
rand_core = { version = "0.6.3", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.26"
tracing = "0.1.28"
tracing-subscriber = "0.2.25"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
zxcvbn = "2.1.1"

[dev-dependencies]
actix-rt = "2.2.0"
regex = "1.5.4"
