[package]
name = "jwk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
der = { version = "0.6.0", features = ["oid", "derive", "alloc"] }
jsonwebtoken = "8.1.1"
openssl = "0.10.41"
serde = { version = "1.0.144", features = ["derive"] }
serde_with = "2.0.0"
thiserror = "1.0.33"

[features]
